version: '3'

services:
  nova:
      build: ./Caracal.Web.Nova.Application
      environment:
        - AppSettings:WorkflowUrl=/api/workflow/[name]
        - AppSettings:Elastic:ServerUrl=http://elk.api:9200
      expose:
        - "80"
      depends_on:
         - elk.api
         - postgres
  workflow.api:
      build: ./Caracal.Web.Nova.Workflow
      ports:
        - "8180:80"
  analytics.api:
      build: ./Caracal.Web.Nova.Analytics
      environment:
          - AppSettings:Elastic:ServerUrl=http://elk.api:9200
      ports:
          - "8280:80"
  elk.api:
      image: sebp/elk
      expose:
              - "5601"
      volumes:
        - /Users/ettienemare/Documents/Development/Data/Nova/ElasticSearch:/var/lib/elasticsearch
  postgres:
      image: postgres
      environment:
        POSTGRES_PASSWORD: Ettiene001
      volumes:
        - /Users/ettienemare/Documents/Development/Data/Nova/Postgres:/var/lib/postgresql/data
      ports:
        - 5432:5432         
  proxy:
      build:
        context:  ./nginx
        dockerfile: Dockerfile
      ports:
        - "80:80"
        - "90:90"
      links:
        - nova