version: '3'

services:
  nova:
      build: ./Caracal.Web.Nova.Application
      environment:
        - AppSettings:WorkflowUrl=/api/workflow/[name]
        - AppSettings:Elastic:ServerUrl=http://elk.api:9200
      ports:
        - "8081:80"
      depends_on:
         - elk.api
         - postgres
         - workflow.api
         - analytics.api
  elk.api:
      image: sebp/elk
      ports:
          - 32781:5601
      volumes:
          - /Users/ettienemare/Documents/Development/Data/ElasticSearch:/var/lib/elasticsearch
  postgres:
      image: postgres
      volumes:
          - /Users/ettienemare/Documents/Development/Data/Nova/Postgres:/var/lib/postgresql/data
      ports:
          - 5432:5432